"use client";

import { ChevronRight, Eye, GripVertical, Sparkles } from "lucide-react";
import React, { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";

import { Hint } from "../../components/ui/hint";
import { cn } from "../../util/cn";
import { EDGE_INSET_PCT, TRACK_SPAN_PCT } from "./Timeline";

/** A canned movement offered for a row, already filtered to ones its transform type can take. */
export type PresetOption = { id: string; label: string; note: string; defaultAmount: number };

export type PresetAxis = "x" | "y" | "z";

export type DopeSheetRow = {
    id: number;
    label: string;
    color: string;
    /** True when the label is user-given (a movement name or a renamed row). */
    named?: boolean;
    /** Frames whose op comes from the sequence's own decoded data — not user-editable. */
    keyframes: number[];
    /** Frames the user has keyed here — draggable and deletable. */
    userKeys?: number[];
    /** Frames generated by tweening between two user keys. */
    tweened?: number[];
    /** Canned movements this row can take, offered in its right-click menu. */
    presets?: PresetOption[];
    /** The movement whose card is selected in the keyframe panel, so the two stay tied together. */
    armed?: boolean;
};

type ContextMenu = { x: number; y: number; group: number; frame: number; hasUserKey: boolean };
/** The preset flyout's live settings while it's open; `to` and `amount` stay strings so the
 *  inputs can be cleared mid-edit without snapping back to a number. */
type PresetDraft = {
    id: string;
    axis: PresetAxis;
    amount: string;
    to: string;
    message: string | null;
};
/**
 * A preset picked from the palette, waiting for the two frames it runs between.
 *
 * Both ends are clicked rather than assumed, so the range is exactly what you pointed at instead
 * of "wherever you let go, to the end of the animation".
 */
type PresetArm = {
    preset: PresetOption;
    /** The row the first click landed on; the second has to be on the same one. */
    row: number | null;
    /** The first frame clicked, or null while still waiting for it. */
    from: number | null;
    /** The frame under the cursor, for the band that previews the range. */
    hover: number | null;
};

type KeyDrag = { group: number; from: number; to: number };
type RowDrag = { id: number; overId: number };

const HIT_RADIUS_PX = 7;

/**
 * The two fixed columns either side of a track, shared with the transport row above so the
 * Timeline and every dope sheet row measure a frame against the exact same pixels.
 *
 * Without the trailing one the tracks would be as much as 170px wider than the Timeline, and the
 * two playheads would drift apart across the reel even though they mean the same frame.
 */
export const TRACK_LABEL_PX = 144;
export const TRACK_TRAILING_PX = 172;

/** Roughly how much room the preset flyout needs, used to pick which side of the menu it opens on. */
const FLYOUT_WIDTH_PX = 224;
const FLYOUT_HEIGHT_PX = 200;

/**
 * A Blender-style dope sheet: one row per transform group, each with diamond markers at the
 * frames it fires on. Label and track live in the same flex row so they scroll together as one
 * unit — splitting them into two independently-scrolling columns was what caused labels and
 * tracks to drift out of sync once there were more rows than fit.
 *
 * Rows can be renamed, hidden, and dragged into any order; user keys can be dragged along their
 * row to retime them, and right-clicking a row opens a menu for the frame under the cursor —
 * including the canned movements, which run from the key you right-clicked.
 */
export function DopeSheet({
    total,
    step,
    rows,
    hiddenCount = 0,
    onScrub,
    onInsertKeyframe,
    onDeleteKeyframe,
    onMoveKeyframe,
    onClearRow,
    onApplyPreset,
    onRenameRow,
    onToggleHidden,
    onReorderRows,
    onShowAllRows,
    onGutterChange,
}: {
    total: number;
    step: number;
    rows: DopeSheetRow[];
    hiddenCount?: number;
    /**
     * How many pixels the rows lose to the scrollbar gutter. The transport row above has to give
     * up the same, or its Timeline is that much wider than every track under it and the two
     * playheads drift apart across the reel.
     */
    onGutterChange?: (px: number) => void;
    onScrub: (n: number) => void;
    onInsertKeyframe?: (group: number, frame: number) => void;
    onDeleteKeyframe?: (group: number, frame: number) => void;
    onMoveKeyframe?: (group: number, from: number, to: number) => void;
    onClearRow?: (group: number) => void;
    /** Writes a preset's keys; returns why it couldn't, or null when it worked. */
    onApplyPreset?: (
        group: number,
        presetId: string,
        axis: PresetAxis,
        amount: number,
        from: number,
        to: number,
    ) => string | null;
    onRenameRow?: (group: number, name: string) => void;
    onToggleHidden?: (group: number) => void;
    onReorderRows?: (fromId: number, toId: number) => void;
    onShowAllRows?: () => void;
}): JSX.Element {
    const draggingScrubRef = useRef(false);
    const keyDragRef = useRef<KeyDrag | null>(null);
    const rowDragRef = useRef<RowDrag | null>(null);
    const [keyDrag, setKeyDrag] = useState<KeyDrag | null>(null);
    const [rowDrag, setRowDrag] = useState<RowDrag | null>(null);
    const [menu, setMenu] = useState<ContextMenu | null>(null);
    const menuRef = useRef<HTMLDivElement>(null);
    const rowsRef = useRef<HTMLDivElement>(null);
    /** Where the menu actually ends up, once it's been measured against the window. */
    const [menuAt, setMenuAt] = useState<{ x: number; y: number } | null>(null);
    const [preset, setPreset] = useState<PresetDraft | null>(null);
    /** A preset picked from the palette, waiting to be given a start and an end. */
    const [arm, setArm] = useState<PresetArm | null>(null);
    // Read from the row handlers, which are defined above the preset logic they need. Refs keep
    // that one-way rather than shuffling half the component around it.
    const armRef = useRef<PresetArm | null>(null);
    armRef.current = arm;
    const pickPresetFrameRef = useRef<
        (row: DopeSheetRow, target: HTMLElement, clientX: number) => void
    >(() => undefined);
    const [renaming, setRenaming] = useState<{ id: number; draft: string } | null>(null);

    // The same inset as the Timeline's, from the same constants, so a frame lands in the same
    // place on both reels.
    const toPct = useCallback(
        (n: number): number =>
            total > 1 ? EDGE_INSET_PCT + (n / (total - 1)) * TRACK_SPAN_PCT : 50,
        [total],
    );

    /** Inverse of `toPct`, so clicking a marker lands on exactly that marker's frame. */
    const frameFromClientX = useCallback(
        (target: HTMLElement, clientX: number): number => {
            if (total <= 1) return 0;
            const rect = target.getBoundingClientRect();
            const pct = ((clientX - rect.left) / rect.width) * 100;
            const frame = Math.round(((pct - EDGE_INSET_PCT) / TRACK_SPAN_PCT) * (total - 1));
            return Math.min(total - 1, Math.max(0, frame));
        },
        [total],
    );

    const hitUserKey = useCallback(
        (row: DopeSheetRow, target: HTMLElement, clientX: number): number | null => {
            const rect = target.getBoundingClientRect();
            const x = clientX - rect.left;
            let best: { frame: number; dist: number } | null = null;
            for (const frame of row.userKeys ?? []) {
                const dist = Math.abs((toPct(frame) / 100) * rect.width - x);
                if (dist <= HIT_RADIUS_PX && (!best || dist < best.dist)) best = { frame, dist };
            }
            return best?.frame ?? null;
        },
        [toPct],
    );

    /** The flyout only exists inside the menu, so the two always come and go together. */
    const closeMenu = useCallback((): void => {
        setMenu(null);
        setPreset(null);
    }, []);

    const onPointerDown = useCallback(
        (event: React.PointerEvent<HTMLDivElement>, row: DopeSheetRow) => {
            if (event.button !== 0) return;
            closeMenu();
            // A preset in hand takes the click: it's marking out a range, not scrubbing.
            if (armRef.current) {
                pickPresetFrameRef.current(row, event.currentTarget, event.clientX);
                return;
            }
            const grabbed = onMoveKeyframe
                ? hitUserKey(row, event.currentTarget, event.clientX)
                : null;
            event.currentTarget.setPointerCapture(event.pointerId);
            if (grabbed !== null) {
                const drag = { group: row.id, from: grabbed, to: grabbed };
                keyDragRef.current = drag;
                setKeyDrag(drag);
                return;
            }
            draggingScrubRef.current = true;
            onScrub(frameFromClientX(event.currentTarget, event.clientX));
        },
        [closeMenu, hitUserKey, onMoveKeyframe, onScrub, frameFromClientX],
    );

    // Pointer capture routes every subsequent move/up back to the row the drag started on, even
    // once the cursor leaves its bounds — so a single shared ref is enough; no need to track
    // which row owns the drag.
    const onPointerMove = useCallback(
        (event: React.PointerEvent<HTMLDivElement>) => {
            const drag = keyDragRef.current;
            if (drag) {
                const to = frameFromClientX(event.currentTarget, event.clientX);
                if (to !== drag.to) {
                    const next = { ...drag, to };
                    keyDragRef.current = next;
                    setKeyDrag(next);
                }
                return;
            }
            if (!draggingScrubRef.current) return;
            onScrub(frameFromClientX(event.currentTarget, event.clientX));
        },
        [onScrub, frameFromClientX],
    );

    const onPointerUp = useCallback(
        (event: React.PointerEvent<HTMLDivElement>) => {
            // Releasing a capture that isn't held throws.
            if (event.currentTarget.hasPointerCapture(event.pointerId)) {
                event.currentTarget.releasePointerCapture(event.pointerId);
            }
            const drag = keyDragRef.current;
            if (drag) {
                keyDragRef.current = null;
                setKeyDrag(null);
                if (drag.to !== drag.from) onMoveKeyframe?.(drag.group, drag.from, drag.to);
                return;
            }
            draggingScrubRef.current = false;
        },
        [onMoveKeyframe],
    );

    /**
     * The reliable end of a drag, whether or not `pointerup` ever arrives — a cancelled gesture,
     * the window losing focus, or a re-render dropping the capture all leave it missing, and the
     * playhead would otherwise keep following the cursor with no button held.
     *
     * A key being dragged is dropped where it got to, the same as a normal release.
     */
    const onDragLost = useCallback(() => {
        const drag = keyDragRef.current;
        draggingScrubRef.current = false;
        if (!drag) return;
        keyDragRef.current = null;
        setKeyDrag(null);
        if (drag.to !== drag.from) onMoveKeyframe?.(drag.group, drag.from, drag.to);
    }, [onMoveKeyframe]);

    const onContextMenu = useCallback(
        (event: React.MouseEvent<HTMLDivElement>, row: DopeSheetRow) => {
            event.preventDefault();
            const frame = frameFromClientX(event.currentTarget, event.clientX);
            const hit = hitUserKey(row, event.currentTarget, event.clientX);
            setPreset(null);
            setMenu({
                x: event.clientX,
                y: event.clientY,
                group: row.id,
                frame: hit ?? frame,
                hasUserKey: hit !== null,
            });
        },
        [frameFromClientX, hitUserKey],
    );

    // ---- Row reordering: drag the grip, drop onto whichever row is under the cursor ----
    const onRowDragStart = useCallback((event: React.PointerEvent<HTMLElement>, id: number) => {
        if (event.button !== 0) return;
        event.preventDefault();
        event.currentTarget.setPointerCapture(event.pointerId);
        rowDragRef.current = { id, overId: id };
        setRowDrag({ id, overId: id });
    }, []);

    const onRowDragMove = useCallback((event: React.PointerEvent<HTMLElement>) => {
        const drag = rowDragRef.current;
        if (!drag) return;
        const el = document.elementFromPoint(event.clientX, event.clientY);
        const rowEl = el?.closest("[data-row-id]");
        const overId = rowEl ? Number(rowEl.getAttribute("data-row-id")) : drag.overId;
        if (!Number.isNaN(overId) && overId !== drag.overId) {
            const next = { ...drag, overId };
            rowDragRef.current = next;
            setRowDrag(next);
        }
    }, []);

    const onRowDragEnd = useCallback(
        (event: React.PointerEvent<HTMLElement>) => {
            event.currentTarget.releasePointerCapture(event.pointerId);
            const drag = rowDragRef.current;
            rowDragRef.current = null;
            setRowDrag(null);
            if (drag && drag.overId !== drag.id) onReorderRows?.(drag.id, drag.overId);
        },
        [onReorderRows],
    );

    // Reports the gutter so the transport row can give up exactly the same width. Watched rather
    // than measured once: it changes with zoom, and with the window on a different display.
    useLayoutEffect(() => {
        const element = rowsRef.current;
        if (!element || !onGutterChange) return;
        const report = (): void => onGutterChange(element.offsetWidth - element.clientWidth);
        report();
        const observer = new ResizeObserver(report);
        observer.observe(element);
        return () => observer.disconnect();
    }, [onGutterChange]);

    /**
     * Keeps the menu on screen. The dope sheet lives at the bottom of the window, so a menu that
     * always opens down and right runs straight off it — which is most right-clicks.
     *
     * Measured rather than guessed, because the menu's height depends on which items that row
     * has. `useLayoutEffect` so the corrected position is what gets painted, with no flicker
     * through the wrong one.
     */
    useLayoutEffect(() => {
        if (!menu) {
            setMenuAt(null);
            return;
        }
        const element = menuRef.current;
        if (!element) return;
        const rect = element.getBoundingClientRect();
        const margin = 8;
        // Flipped to the other side of the cursor when it won't fit, then clamped in case it
        // doesn't fit either way.
        const x =
            menu.x + rect.width + margin > window.innerWidth
                ? Math.max(margin, menu.x - rect.width)
                : menu.x;
        const y =
            menu.y + rect.height + margin > window.innerHeight
                ? Math.max(margin, menu.y - rect.height)
                : menu.y;
        setMenuAt({ x, y });
    }, [menu]);

    useEffect(() => {
        if (!menu) return;
        const onKey = (event: KeyboardEvent): void => {
            if (event.key === "Escape") closeMenu();
        };
        window.addEventListener("pointerdown", closeMenu);
        window.addEventListener("keydown", onKey);
        return () => {
            window.removeEventListener("pointerdown", closeMenu);
            window.removeEventListener("keydown", onKey);
        };
    }, [menu, closeMenu]);

    const commitRename = useCallback(() => {
        if (renaming) onRenameRow?.(renaming.id, renaming.draft);
        setRenaming(null);
    }, [renaming, onRenameRow]);
    // ---- Applying a preset by clicking its two ends ---------------------------------------

    /** Every preset any row can take, so the palette shows one button per kind of movement. */
    const palette = useMemo(() => {
        const seen = new Map<string, PresetOption>();
        for (const row of rows) for (const preset of row.presets ?? []) seen.set(preset.id, preset);
        return Array.from(seen.values());
    }, [rows]);

    /** Picking a preset, or clicking the armed one again to put it back. */
    const armPreset = useCallback((preset: PresetOption) => {
        setArm((current) =>
            current?.preset.id === preset.id
                ? null
                : { preset, row: null, from: null, hover: null },
        );
    }, []);

    /** Whether a row's transform type can take whatever is armed. */
    const rowTakesArmed = useCallback(
        (row: DopeSheetRow): boolean =>
            arm !== null && (row.presets ?? []).some((p) => p.id === arm.preset.id),
        [arm],
    );

    /**
     * One end of the range. Snaps to a key when the click lands near one, so "click two
     * keyframes" does exactly that; anywhere else on the row is taken at face value.
     */
    const pickPresetFrame = useCallback(
        (row: DopeSheetRow, target: HTMLElement, clientX: number): void => {
            if (!arm || !rowTakesArmed(row)) return;
            const frame = hitUserKey(row, target, clientX) ?? frameFromClientX(target, clientX);

            // A click on a different row starts the range again there rather than spanning two.
            if (arm.from === null || arm.row !== row.id) {
                setArm({ ...arm, row: row.id, from: frame, hover: frame });
                return;
            }
            onApplyPreset?.(
                row.id,
                arm.preset.id,
                "y",
                arm.preset.defaultAmount,
                Math.min(arm.from, frame),
                Math.max(arm.from, frame),
            );
            setArm(null);
        },
        [arm, frameFromClientX, hitUserKey, onApplyPreset, rowTakesArmed],
    );
    pickPresetFrameRef.current = pickPresetFrame;

    // Escape puts the preset back, the same as every other half-finished thing here.
    useEffect(() => {
        if (!arm) return;
        const onKey = (event: KeyboardEvent): void => {
            if (event.key === "Escape") setArm(null);
        };
        window.addEventListener("keydown", onKey);
        return () => window.removeEventListener("keydown", onKey);
    }, [arm]);

    if (rows.length === 0 && hiddenCount === 0) {
        return (
            <p className="text-xs text-muted-foreground">
                No transform groups fire in this sequence yet.
            </p>
        );
    }

    return (
        <div className="flex flex-col">
            {hiddenCount > 0 ? (
                <div className="mb-1 flex items-center gap-2 text-[10px] text-muted-foreground">
                    <span>
                        {hiddenCount} layer{hiddenCount === 1 ? "" : "s"} hidden
                    </span>
                    <button
                        type="button"
                        className="underline hover:text-foreground"
                        onClick={onShowAllRows}
                    >
                        Show all
                    </button>
                </div>
            ) : null}

            <div className="flex gap-3">
                {/* The gutter is reserved whether or not it scrolls, so the tracks don't jump sideways
                by a scrollbar's width the moment there are enough layers to need one. Its width
                is measured rather than assumed — it's a platform detail, not a constant. */}
                <div
                    ref={rowsRef}
                    className="flex max-h-40 min-w-0 flex-1 flex-col gap-0.5 overflow-y-auto"
                    style={{ scrollbarGutter: "stable" }}
                >
                    {rows.map((row) => {
                        const dragging = keyDrag?.group === row.id ? keyDrag : null;
                        const userKeys = (row.userKeys ?? []).filter(
                            (f) => !dragging || f !== dragging.from,
                        );
                        const isDragged = rowDrag?.id === row.id;
                        const isDropTarget =
                            rowDrag !== null && rowDrag.overId === row.id && rowDrag.id !== row.id;
                        const takesArmed = rowTakesArmed(row);
                        // Only once the first end is down, and only on the row it went down on.
                        const armBand =
                            arm && arm.row === row.id && arm.from !== null
                                ? {
                                      row: row.id,
                                      from: Math.min(arm.from, arm.hover ?? arm.from),
                                      to: Math.max(arm.from, arm.hover ?? arm.from),
                                  }
                                : null;
                        return (
                            // Same columns and gaps as the transport row above, so this row's track
                            // starts and ends at the exact same x as the Timeline bar — otherwise the
                            // two playheads drift apart even though they mean the same frame.
                            <div
                                key={row.id}
                                data-row-id={row.id}
                                className={cn(
                                    "group/row flex h-5 shrink-0 items-center gap-3 rounded-sm",
                                    isDragged && "opacity-40",
                                    isDropTarget && "ring-1 ring-[#e87d0d]",
                                    // Ties the row to the movement card selected in the panel, so
                                    // clicking one shows you which reel it belongs to.
                                    row.armed && "bg-[#e87d0d]/10",
                                )}
                            >
                                <div
                                    className="flex shrink-0 items-center gap-1 overflow-hidden text-[11px]"
                                    style={{ width: TRACK_LABEL_PX }}
                                >
                                    <Hint
                                        heading="Reorder"
                                        detail="Drag this row into any position"
                                        label="Drag to reorder"
                                    >
                                        <button
                                            type="button"
                                            onPointerDown={(e) => onRowDragStart(e, row.id)}
                                            onPointerMove={onRowDragMove}
                                            onPointerUp={onRowDragEnd}
                                            className="shrink-0 cursor-grab text-muted-foreground/50 opacity-0 hover:text-foreground group-hover/row:opacity-100 active:cursor-grabbing"
                                        >
                                            <GripVertical className="size-3" />
                                        </button>
                                    </Hint>
                                    <span
                                        className="size-2 shrink-0 rounded-full"
                                        style={{ backgroundColor: row.color }}
                                    />
                                    {renaming?.id === row.id ? (
                                        <input
                                            autoFocus
                                            value={renaming.draft}
                                            onChange={(e) =>
                                                setRenaming({ id: row.id, draft: e.target.value })
                                            }
                                            onBlur={commitRename}
                                            onKeyDown={(e) => {
                                                if (e.key === "Enter") commitRename();
                                                else if (e.key === "Escape") setRenaming(null);
                                            }}
                                            className="h-4 min-w-0 flex-1 rounded border border-border/60 bg-card px-1 text-[11px]"
                                        />
                                    ) : (
                                        <Hint heading={row.label} detail="Double-click to rename">
                                            <span
                                                className={cn(
                                                    "min-w-0 flex-1 cursor-text truncate",
                                                    row.armed
                                                        ? "font-medium text-[#e87d0d]"
                                                        : row.named
                                                        ? "text-foreground"
                                                        : "text-muted-foreground",
                                                )}
                                                onDoubleClick={() =>
                                                    setRenaming({ id: row.id, draft: row.label })
                                                }
                                            >
                                                {row.label}
                                            </span>
                                        </Hint>
                                    )}
                                    {onToggleHidden ? (
                                        <Hint
                                            heading="Hide"
                                            detail="Takes this row off the timeline. Its keys stay."
                                            label={`Hide ${row.label}`}
                                        >
                                            <button
                                                type="button"
                                                onClick={() => onToggleHidden(row.id)}
                                                className="shrink-0 text-muted-foreground/60 opacity-0 hover:text-foreground group-hover/row:opacity-100"
                                            >
                                                <Eye className="size-3" />
                                            </button>
                                        </Hint>
                                    ) : null}
                                </div>
                                <div
                                    data-track-row={row.id}
                                    // The transparent border matters: the Timeline's track has a real
                                    // one, and `left: %` measures from the padding box — so without
                                    // it every frame here sits a pixel off from the same frame there.
                                    className={cn(
                                        "relative h-5 flex-1 touch-none select-none overflow-hidden rounded border bg-background/60",
                                        // While a preset is in hand the rows that can take it stand
                                        // out and the rest are plainly not options.
                                        arm
                                            ? takesArmed
                                                ? "cursor-crosshair border-[#e87d0d]/60"
                                                : "cursor-not-allowed border-transparent opacity-40"
                                            : "cursor-pointer border-transparent",
                                    )}
                                    onPointerDown={(e) => onPointerDown(e, row)}
                                    onPointerMove={(e) => {
                                        if (arm && takesArmed) {
                                            const frame = frameFromClientX(
                                                e.currentTarget,
                                                e.clientX,
                                            );
                                            setArm((current) =>
                                                current && current.hover !== frame
                                                    ? { ...current, hover: frame }
                                                    : current,
                                            );
                                            return;
                                        }
                                        onPointerMove(e);
                                    }}
                                    onPointerUp={onPointerUp}
                                    onLostPointerCapture={onDragLost}
                                    onPointerCancel={onDragLost}
                                    onContextMenu={(e) => onContextMenu(e, row)}
                                >
                                    {/* The range so far: from the first click to wherever the cursor
                                    is, so the second click isn't a guess. */}
                                    {armBand && armBand.row === row.id ? (
                                        <div
                                            className="pointer-events-none absolute inset-y-0 bg-[#e87d0d]/25"
                                            style={{
                                                left: `${toPct(armBand.from)}%`,
                                                width: `${
                                                    toPct(armBand.to) - toPct(armBand.from)
                                                }%`,
                                            }}
                                        />
                                    ) : null}
                                    {/* Centred on the frame, the same as the Timeline's playhead —
                                    drawn from the left edge it sits half a pixel to the right. */}
                                    <div
                                        className="pointer-events-none absolute inset-y-0 w-px -translate-x-1/2 bg-[#5680c2]"
                                        style={{ left: `${toPct(step)}%` }}
                                    />
                                    {(row.tweened ?? []).map((f) => (
                                        <div
                                            key={`t${f}`}
                                            className="pointer-events-none absolute top-1/2 size-1 -translate-x-1/2 -translate-y-1/2 rounded-full opacity-50"
                                            style={{
                                                left: `${toPct(f)}%`,
                                                backgroundColor: row.color,
                                            }}
                                        />
                                    ))}
                                    {/* A key sitting exactly where the playhead is gets a white ring:
                                    that's the one the panel is editing, and "which key am I on"
                                    is otherwise a matter of squinting at the line. */}
                                    {row.keyframes.map((f) => (
                                        <div
                                            key={f}
                                            className={cn(
                                                "pointer-events-none absolute top-1/2 -translate-x-1/2 -translate-y-1/2 rotate-45",
                                                f === step
                                                    ? "size-2.5 ring-1 ring-white"
                                                    : "size-2",
                                            )}
                                            style={{
                                                left: `${toPct(f)}%`,
                                                backgroundColor: row.color,
                                            }}
                                        />
                                    ))}
                                    {userKeys.map((f) => (
                                        <div
                                            key={`u${f}`}
                                            className={cn(
                                                "pointer-events-none absolute top-1/2 -translate-x-1/2 -translate-y-1/2 rotate-45 bg-[#e87d0d]",
                                                f === step
                                                    ? "size-3 border border-white shadow-[0_0_0_1px_rgba(0,0,0,0.6)]"
                                                    : "size-2.5 border border-black/40",
                                            )}
                                            style={{ left: `${toPct(f)}%` }}
                                        />
                                    ))}
                                    {dragging ? (
                                        <div
                                            className="pointer-events-none absolute top-1/2 size-2.5 -translate-x-1/2 -translate-y-1/2 rotate-45 border border-white/70 bg-[#e87d0d]"
                                            style={{ left: `${toPct(dragging.to)}%` }}
                                        />
                                    ) : null}
                                </div>
                            </div>
                        );
                    })}
                </div>

                {/* Where the transport row's counter and frame controls sit, so the tracks stop at
                the same x as the Timeline. */}
                <div className="shrink-0" style={{ width: TRACK_TRAILING_PX }}>
                    {palette.length > 0 && onApplyPreset ? (
                        <PresetPalette presets={palette} arm={arm} onArm={armPreset} />
                    ) : null}
                </div>
            </div>

            {menu ? (
                <div
                    ref={menuRef}
                    className="fixed z-50 min-w-44 rounded-md border border-border bg-card py-1 text-xs shadow-xl"
                    style={{ left: menuAt?.x ?? menu.x, top: menuAt?.y ?? menu.y }}
                    onPointerDown={(e) => e.stopPropagation()}
                >
                    <p className="px-2 pb-1 text-[10px] uppercase tracking-wide text-muted-foreground">
                        Frame {menu.frame}
                    </p>
                    {menu.hasUserKey ? (
                        <button
                            type="button"
                            className="block w-full px-2 py-1 text-left hover:bg-[#e87d0d]/15"
                            onClick={() => {
                                onDeleteKeyframe?.(menu.group, menu.frame);
                                closeMenu();
                            }}
                        >
                            Delete keyframe
                        </button>
                    ) : (
                        <button
                            type="button"
                            className="block w-full px-2 py-1 text-left hover:bg-[#e87d0d]/15"
                            onClick={() => {
                                onInsertKeyframe?.(menu.group, menu.frame);
                                closeMenu();
                            }}
                        >
                            Insert keyframe
                        </button>
                    )}
                    <button
                        type="button"
                        className="block w-full px-2 py-1 text-left hover:bg-[#e87d0d]/15"
                        onClick={() => {
                            onScrub(menu.frame);
                            closeMenu();
                        }}
                    >
                        Jump to frame
                    </button>

                    {onApplyPreset ? (
                        <PresetMenuItem
                            presets={rows.find((r) => r.id === menu.group)?.presets ?? []}
                            from={menu.frame}
                            lastFrame={Math.max(0, total - 1)}
                            draft={preset}
                            onChange={setPreset}
                            onApply={(presetId, axis, amount, to) => {
                                const problem = onApplyPreset(
                                    menu.group,
                                    presetId,
                                    axis,
                                    amount,
                                    menu.frame,
                                    to,
                                );
                                if (problem === null) closeMenu();
                                else setPreset((d) => (d ? { ...d, message: problem } : d));
                            }}
                        />
                    ) : null}

                    <div className="my-1 border-t border-border/60" />
                    <button
                        type="button"
                        className="block w-full px-2 py-1 text-left hover:bg-[#e87d0d]/15"
                        onClick={() => {
                            const row = rows.find((r) => r.id === menu.group);
                            setRenaming({ id: menu.group, draft: row?.label ?? "" });
                            closeMenu();
                        }}
                    >
                        Rename layer
                    </button>
                    <button
                        type="button"
                        className="block w-full px-2 py-1 text-left hover:bg-[#e87d0d]/15"
                        onClick={() => {
                            onToggleHidden?.(menu.group);
                            closeMenu();
                        }}
                    >
                        Hide layer
                    </button>
                    {onClearRow ? (
                        <button
                            type="button"
                            className="block w-full px-2 py-1 text-left text-destructive hover:bg-destructive/15"
                            onClick={() => {
                                onClearRow(menu.group);
                                closeMenu();
                            }}
                        >
                            Clear all keys on this row
                        </button>
                    ) : null}
                </div>
            ) : null}
        </div>
    );
}

/**
 * The presets, as things you can pick up.
 *
 * Dragging one onto a row is the short way to "make this move": no menu, and the row you drop on
 * is the row it applies to. The right-click flyout is still there for choosing an axis, an
 * amount and an end frame — this is the version for when the defaults will do.
 */
function PresetPalette({
    presets,
    arm,
    onArm,
}: {
    presets: PresetOption[];
    arm: PresetArm | null;
    onArm: (preset: PresetOption) => void;
}): JSX.Element {
    return (
        <div className="flex h-full flex-col gap-0.5 overflow-y-auto">
            <p className="flex items-center gap-1 truncate text-[10px] uppercase tracking-wide text-muted-foreground/70">
                <Sparkles className="size-2.5 shrink-0" />
                {arm === null
                    ? "movement presets"
                    : arm.from === null
                    ? "click the start"
                    : "click the end"}
            </p>
            {presets.map((preset) => {
                const armed = arm?.preset.id === preset.id;
                return (
                    <Hint
                        key={preset.id}
                        side="left"
                        heading={preset.label}
                        detail={
                            armed
                                ? "Click two frames on a row to set where it runs — Esc to put it back"
                                : `${preset.note}. Click to pick it up.`
                        }
                    >
                        <button
                            type="button"
                            aria-pressed={armed}
                            onClick={() => onArm(preset)}
                            className={cn(
                                "flex h-5 shrink-0 items-center truncate rounded border px-1.5 text-[10px] transition-colors",
                                armed
                                    ? "border-[#e87d0d] bg-[#e87d0d] font-medium text-black"
                                    : "border-border/60 bg-background text-muted-foreground hover:border-[#e87d0d]/60 hover:text-foreground",
                            )}
                        >
                            {preset.label}
                        </button>
                    </Hint>
                );
            })}
        </div>
    );
}

/**
 * The "Movement preset" entry in a row's right-click menu, plus the flyout it opens.
 *
 * The preset runs from the key you right-clicked, so there's no "first frame" to fill in — only
 * where it ends, which direction it goes, and how far. What it writes is ordinary keyframes.
 */
function PresetMenuItem({
    presets,
    from,
    lastFrame,
    draft,
    onChange,
    onApply,
}: {
    presets: PresetOption[];
    from: number;
    lastFrame: number;
    draft: PresetDraft | null;
    onChange: (draft: PresetDraft | null) => void;
    onApply: (presetId: string, axis: PresetAxis, amount: number, to: number) => void;
}): JSX.Element {
    const anchorRef = useRef<HTMLDivElement | null>(null);
    // The menu opens wherever you right-clicked, which near an edge leaves no room on the usual
    // side; measured once the flyout exists, so it lands on whichever side actually fits.
    const [flip, setFlip] = useState({ x: false, y: false });

    useLayoutEffect(() => {
        const anchor = anchorRef.current;
        if (!draft || !anchor) return;
        const rect = anchor.getBoundingClientRect();
        setFlip({
            x: rect.right + FLYOUT_WIDTH_PX + 8 > window.innerWidth,
            y: rect.top + FLYOUT_HEIGHT_PX > window.innerHeight,
        });
    }, [draft]);

    if (presets.length === 0) {
        return (
            <p
                className="px-2 py-1 text-muted-foreground/50"
                title="Presets are shaped for rotate, translate and scale movements — this row is neither."
            >
                No presets for this movement
            </p>
        );
    }

    const selected = presets.find((p) => p.id === draft?.id) ?? presets[0];

    return (
        <div ref={anchorRef} className="relative">
            <button
                type="button"
                className="flex w-full items-center gap-1.5 px-2 py-1 text-left hover:bg-[#e87d0d]/15"
                onClick={() =>
                    onChange(
                        draft
                            ? null
                            : {
                                  id: presets[0].id,
                                  axis: "y",
                                  amount: String(presets[0].defaultAmount),
                                  to: String(lastFrame),
                                  message: null,
                              },
                    )
                }
            >
                <Sparkles className="size-3 shrink-0 text-muted-foreground" />
                Movement preset
                <ChevronRight
                    className={cn("ml-auto size-3 transition-transform", draft && "rotate-90")}
                />
            </button>

            {draft ? (
                <div
                    className={cn(
                        "absolute z-10 rounded-md border border-border bg-card p-1.5 shadow-xl",
                        flip.x ? "right-full mr-1" : "left-full ml-1",
                        flip.y ? "bottom-0" : "top-0",
                    )}
                    style={{ width: FLYOUT_WIDTH_PX }}
                >
                    <div className="max-h-28 overflow-y-auto">
                        {presets.map((p) => (
                            <button
                                key={p.id}
                                type="button"
                                className={cn(
                                    "block w-full rounded px-1.5 py-1 text-left",
                                    selected.id === p.id
                                        ? "bg-[#e87d0d]/20 text-foreground"
                                        : "hover:bg-[#e87d0d]/10",
                                )}
                                onClick={() =>
                                    onChange({
                                        ...draft,
                                        id: p.id,
                                        amount: String(p.defaultAmount),
                                        message: null,
                                    })
                                }
                            >
                                {p.label}
                                <span className="block text-[10px] text-muted-foreground">
                                    {p.note}
                                </span>
                            </button>
                        ))}
                    </div>

                    <div className="mt-1.5 flex items-center gap-1 border-t border-border/60 pt-1.5">
                        <span className="text-muted-foreground">axis</span>
                        {(["x", "y", "z"] as const).map((axis) => (
                            <button
                                key={axis}
                                type="button"
                                aria-label={`Axis ${axis.toUpperCase()}`}
                                aria-pressed={draft.axis === axis}
                                className={cn(
                                    "size-5 rounded border border-border/60 uppercase",
                                    draft.axis === axis
                                        ? "bg-[#e87d0d] text-black"
                                        : "hover:bg-[#e87d0d]/15",
                                )}
                                onClick={() => onChange({ ...draft, axis, message: null })}
                            >
                                {axis}
                            </button>
                        ))}
                        <span className="ml-1 text-muted-foreground">amount</span>
                        <input
                            type="number"
                            value={draft.amount}
                            aria-label="Preset amount"
                            onChange={(e) =>
                                onChange({ ...draft, amount: e.target.value, message: null })
                            }
                            className="no-spinner h-5 w-12 rounded border border-border/60 bg-background px-1 font-mono"
                        />
                    </div>

                    <div className="mt-1 flex items-center gap-1">
                        <span className="text-muted-foreground">frames {from} to</span>
                        <input
                            type="number"
                            value={draft.to}
                            aria-label="Preset last frame"
                            onChange={(e) =>
                                onChange({ ...draft, to: e.target.value, message: null })
                            }
                            className="no-spinner h-5 w-12 rounded border border-border/60 bg-background px-1 font-mono"
                        />
                        <button
                            type="button"
                            className="ml-auto rounded bg-[#e87d0d] px-2 py-0.5 font-medium text-black"
                            onClick={() => {
                                const amount = Number.parseInt(draft.amount, 10);
                                const to = Number.parseInt(draft.to, 10);
                                onApply(
                                    selected.id,
                                    draft.axis,
                                    Number.isNaN(amount) ? selected.defaultAmount : amount,
                                    Number.isNaN(to) ? lastFrame : to,
                                );
                            }}
                        >
                            Apply
                        </button>
                    </div>

                    {draft.message ? (
                        <p className="mt-1 text-[10px] text-destructive">{draft.message}</p>
                    ) : null}
                </div>
            ) : null}
        </div>
    );
}
